### ISSUE TITLE
Tentative roadmap

### ISSUE THREAD

**Issue by jfbercher** [jfbercher/jupyter_varInspector#1]
This is a tentative roadmap to add multiple kernels support in the `varInspector` nbextension (feel free to improve)

- [x] transform the python code to return a JSON array of var objects with all variables and keys name, type, size, repr
- [x] add js code to create the html table from the JSON array
- [x] read python code from a file? a json representation in the yaml config file?
- [x] read python code for deleting selected variables (when pressing the x in window)
- [x] add code for say R, which returns a JSOn array of var objects as before
- [x] add R code for deleting a variable
- [x] add code  to check that that the running kernel is supported
- [x] documentation on how to add support for other kernels 

Other enhancements
- [ ] replace `delete links` in the html table by pretty buttons

**Comment by jcb91** [comment]
looks like most of these are done already :)

**Comment by clayms** [comment]
I would like to add code for pySpark which returns a JSON array or var objects as the `var_list.py` and `var_list.r` do for Python and R, respectively.

As pySpark files are also `.py`, then this would be called `var_list_spark.py`  

I am guessing that the "json object defining the libraries to load, the delete/remove kernel commands to delete a variable, and finally the commands to refresh the list of variables" would also need to be updated.

**Comment by jcb91** [comment]
> I am guessing that the "json object defining the libraries to load, the delete/remove kernel commands to delete a variable, and finally the commands to refresh the list of variables" would also need to be updated.

Yes, it would make sense to add config settings for the pyspark kernel both in the yaml file (which declares the default value for the configurator, but doesn't actually get used by the extension itself) and in the main.js file (which contains the defaults which actually get used).
